apiVersion: apps/v1
kind: Deployment
metadata:
  name: athul-s-world 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: athul-s-world
  template:
    metadata:
      labels:
        app: athul-s-world
    spec:
      containers:
      - name: athul-s-app
        image: gcr.io/google-samples/hello-app:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
