apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: athul-s-world
    run: athul-s-world-pod
  name: athul-s-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: athul-s-world
  template:
    metadata:
      labels:
        app: athul-s-world
    spec:
      containers:
      - image: docker.io/athulmul/my-pvt-test-repo:v2
        name: hello-app
        resources:          
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
        - name:  pvt-registry-credentials-2

