apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: athul-s-world
    run: athul-s-world-pod
  name: athul-s-world
spec:
  progressDeadlineSeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: athul-s-world
  template:
    metadata:
      labels:
        app: athul-s-world
    spec:
      containers:
      - image: gcr.io/google-samples/hellasdo-app:1.0
        name: hello-app
        resources:          
          limits:
            memory: "128Mi"
            cpu: "500m"

