apiVersion: v1
kind: Pod
metadata:
  name: init-containers

spec:
  initContainers:
    - name: init-service
      image: marketplace.gcr.io/google/ubuntu1804
      command: ["sh", "-c", "echo waiting for service; sleep 2"]
    - name: init-badatase
      image: marketplace.gcr.io/google/ubuntu1804
      command: ["sh", "-c", "echo waiting for db; sleep 2"]
  containers:
  - name: myapp
    image: gcr.io/google-samples/hello-app:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
