apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod-1
  labels:
    app: hello-world
    deployment: v1
    tier: production
spec:
  containers:
  - name: ngnix
    image:  marketplace.gcr.io/google/nginx1:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  # this is a dummy value for now
  # add a lable (key: value) on the node level and then specify it here
  # to allocate pods to the matching node
  nodeSelector:
    hardware: testing-at-test

---
apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod-2
  labels:
    app: hello-world
    deployment: v1.1
    tier: production
spec:
  containers:
  - name: ngnix
    image: marketplace.gcr.io/google/nginx1:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod-3
  labels:
    app: hello-world
    deployment: v1.1
    tier: qa
spec:
  containers:
  - name: ngnix
    image: marketplace.gcr.io/google/nginx1:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


--- 


apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod-4
  labels:
    app: hello-world-admin
    deployment: v1.1
    tier: production
spec:
  containers:
  - name: ngnix
    image: marketplace.gcr.io/google/nginx1:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

