apiVersion: v1
kind: Service
metadata:
  labels:
    app: athul-s-world
  name: athul-s-world-node-port
spec:
  ports:
  - name: node-port-service
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: athul-s-world  
  type: NodePort
  
