apiVersion: v1
kind: Service
metadata:
  labels:
    app: athul-s-world
  name: athul-s-world-cluster-ip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080 
    name: cluster-ip-service
  selector:
    app: athul-s-world
   
