apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-wp
  labels:
    app: wordpress
provisioner:  kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none