apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: wp-pv-claim
  gcePersistentDisk:
    pdName: wavescale-nfs-vm-test
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi