apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: wp-pv-claim
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/simple-wp
    server: 34.90.40.207
    readOnly: false


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi